### ISSUE TITLE
Price limits aren't taken into account when setting

### ISSUE THREAD

**Issue by jmmontalvo** [StockDrops/StockDropsPublicDesktopApp#10]
This happened when Best Buy was alerting of sales but I would get all GPU's in a certain category (all 3080s for example) even though some were over my limit. I definitely turned off the Zotac GPUs but I'm not sure if that was what caused the bug or the other bug I mentioned in a different issue report about alert gui messing up after updating.

**Comment by emorell96** [comment]
Price limits are not available yet with Best Buy this is because we lack pricing information on Best Buy, we only have stock information. We will find a solution on v1.3.8
