### ISSUE TITLE
the expiration date for this version has been reached

### ISSUE THREAD

**Issue by WIMMPYIII** [StockDrops/StockDropsPublicDesktopApp#17]
the expiration date for this version has been reached you need to update to the latest version to use this software. I get this now when I try and load the app.
Tried unistall and downlaod from the web and does the same thing. Just gave me this error tonight.

**Comment by emorell96** [comment]
Hi make sure to update to the latest version 2.6.0. We addressed this issue there.

You can find that version here: https://github.com/StockDrops/StockDropsPublicDesktopApp/releases/download/v2.6.0/Setup.exe

Or https://files.stockdrops.net/releases/latest/setup.exe

**Comment by emorell96** [comment]
That version will ask you to install the net6.0 framework which you can get at https://get.dot.net (download the runtime not the sdk - unless you also want to develop net6.0 apps).

Version 2.6.1 which I'm publishing in about 20 minutes will include it by default.

**Comment by emorell96** [comment]
Latest version here: https://github.com/StockDrops/StockDropsPublicDesktopApp/releases/download/v2.6.0/Setup.exe
This has been solved but I'm leaving this open for people to be able to reference the solution easily.
