### ISSUE TITLE
XFX - Speedster MERC319 AMD Radeon RX 6700 XT

### ISSUE THREAD

**Issue by nwalk7800** [StockDrops/StockDropsPublicDesktopApp#18]
I keep getting notifications for this card on Best Buy even though I'm not monitoring for it and it's not in stock.

![image](https://user-images.githubusercontent.com/1247667/148120652-b1474b9f-f02b-432b-92d6-94a98e26ed29.png)

![image](https://user-images.githubusercontent.com/1247667/148120595-11fb81f0-850d-4f93-ac45-469b7b8c6ce2.png)

![image](https://user-images.githubusercontent.com/1247667/148120535-cccdd363-1f50-468b-9729-5112d683b891.png)

**Comment by emorell96** [comment]
What's the Best Buy Sku? Thanks!

**Comment by nwalk7800** [comment]
6457619
