### ISSUE TITLE
Portable only Install

### ISSUE THREAD

**Issue by davidbuckleyni** [StockDrops/StockDropsPublicDesktopApp#3]
Please provide a portable only .zip file where one can simply run the exe. Most users these days dont like running installer.

**Comment by emorell96** [comment]
The installer is portable, i.e. it is a self extracting exe. That will extract the application in %localappdata%/StockDropsApp

**Comment by emorell96** [comment]
(it will not need any UAC prompts)

**Comment by emorell96** [comment]
The exe is needed since it's an essential part of the automatic update system the app uses called Squirrel.Windows (open source).
