### ISSUE TITLE
Missing Selection of inventory after retail update from 1.1.3 -> 1.1.5

### ISSUE THREAD

**Issue by JustinPullen** [StockDrops/StockDropsPublicDesktopApp#5]
Once updated my alert selection tab no longer has any options besides NewEgg

I previously only had 3080 FE selected under the bronze tier with both items under that model selected. 

![image](https://user-images.githubusercontent.com/5048862/118729572-c71a5c80-b7fb-11eb-80cc-1d1cd4b57ecb.png)

**Comment by emorell96** [comment]
Upload the file inside this zip to %localappdata%/stockdrops
[app.zip](https://github.com/StockDrops/StockDropsPublicDesktopApp/files/6504689/app.zip)

**Comment by JustinPullen** [comment]
Yep that DB fixed my issue. 

Notes:
I had the app running,  Saw the discord ping,  Went to the app, and clicked "check for update" in the settings.  SD opened two windows at that point, I thought that was weird so I closed one....so there is a chance I killed it in the middle of the DB Migration. 

But yea that fixed it without a fresh install.   

Thanks!

**Comment by JustinPullen** [comment]
One more note. I had to resubscribe to my alerts. 

To be expected when overwriting the local DB.

**Comment by emorell96** [comment]
Fixed in https://github.com/StockDrops/StockDropsPublicDesktopApp/releases/tag/v1.1.6
