### ISSUE TITLE
1.1.5 Alert settings mostly blank

### ISSUE THREAD

**Issue by GallaherMike** [StockDrops/StockDropsPublicDesktopApp#6]
The alert setting is missing most of the content in 1.1.5 some headings appear and the Newegg option, but that is it. 

![image](https://user-images.githubusercontent.com/636820/118732089-92ec6f00-b7ee-11eb-85ae-36720df228aa.png)

**Comment by emorell96** [comment]
See https://github.com/StockDrops/StockDropsPublicDesktopApp/issues/5 please don't close this issue so that people can see it.

**Comment by GallaherMike** [comment]
Thanks, Justin beat me to the post. 

Nice app, keep up the good work.

**Comment by emorell96** [comment]
Thank you! I have addressed this issue in https://github.com/StockDrops/StockDropsPublicDesktopApp/releases/tag/v1.1.6
