### ISSUE TITLE
Updating software resets alert preferences gui (somewhat)

### ISSUE THREAD

**Issue by jmmontalvo** [StockDrops/StockDropsPublicDesktopApp#9]
Updating the app seems to leave the preference file (or whatever you guys use) and it resets the alert settings gui so I had to re-fill in whatever I want alerts on when I wanted to update alert preferences (I still got the same alerts before noticing that the gui was off which leads me to believe it's a gui issue)

**Comment by emorell96** [comment]
That only happens on select updates where we need to remake the database holding your settings.
